dependencies:
  - safe-global/safe-contracts@1.3.0
compiler:
  solc:
    remappings:
      - "@safe-global=safe-global/safe-contracts@1.3.0"

# gnosis safe v1.3 assets: https://github.com/gnosis/safe-deployments/tree/main/src/assets/v1.3.0
networks:
  default: arbitrum-main-fork
  arbitrum-main:
    gnosis_safe: "0x3E5c63644E683549055b9Be8653de26E0B4CD36E"
    gnosis_proxy_factory: "0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2"
    gnosis_fallback: "0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4"
  arbitrum-main-fork:
    gnosis_safe: "0x3E5c63644E683549055b9Be8653de26E0B4CD36E"
    gnosis_proxy_factory: "0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2"
    gnosis_fallback: "0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4"
  arbitrum-test:
    gnosis_safe: "0x3E5c63644E683549055b9Be8653de26E0B4CD36E"
    gnosis_proxy_factory: "0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2"
    gnosis_fallback: "0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4"

dotenv: .env

# Development Wallets. Live wallets are loaded from Brownie accounts
wallets:
  owner1: ${SAFE_OWNER_1}
  owner2: ${SAFE_OWNER_2}
